### ISSUE TITLE
Segfault with bufferedao extension enabled in setup.py

### ISSUE THREAD

**Issue by wimstefan** [joerg-lehmann/PyTone#4]
With `buildbufferedaoext = True` in setup.py I first run the build scripts with `python3 ./setup.py build_ext -i` and then run the application with `./pytone -c conf/pytonerc` I get a segfault. The logfile is attached below: 
[2019-11-26-segfault-with-bufferedao.log](https://github.com/joerg-lehmann/PyTone/files/3896781/2019-11-26-segfault-with-bufferedao.log)

To get more information about the segfault I've added the following lines to `src/pytone.py` with the help of @altendky 
```diff
  diff --git a/src/pytone.py b/src/pytone.py
  index 8ed3501..191b883 100755
  --- a/src/pytone.py
  +++ b/src/pytone.py
  @@ -26,6 +26,7 @@ if sys.hexversion < 0x03050000:

   import curses, os, os.path, signal
   import importlib, importlib.util
  +import faulthandler; faulthandler.enable()

   ##############################################################################
   # gettext initialization.
```
Please let me know if you need more information.

**Comment by joerg-lehmann** [comment]
Thanks, Stefan for rereporting this. The output from the faulthandler looks like the segfault is happening during import of the bufferedao module. I do not have this problem with Python 3.7, but I do not think that this is related to the specific Python 3 version. It could also be a race condition - making it harder to debug.

I pushed a branch debug_bufferedao with some simple initial debug output. Maybe you can try running this and report up to which number (you should see) you come.

**Comment by wimstefan** [comment]
Thank you so much Joerg for taking the time and look into it!
Here is the output of the segfault I'm getting:
[2019-11-28-segfault-with-debug-bufferedao.log](https://github.com/joerg-lehmann/PyTone/files/3899246/2019-11-28-segfault-with-debug-bufferedao.log)

**Comment by joerg-lehmann** [comment]
Stefan, sorry for being late in replying. I would need the console (stdout) output. Would you manage to catch that?

**Comment by wimstefan** [comment]
> Stefan, sorry for being late in replying. I would need the console (stdout) output. Would you manage to catch that?

Hi Joerg, no worries :)
The last line in the log I've posted is actually all of the stdout output I catched. Or do I misunderstand your question and use another way than `./pytone -c conf/pytonerc` for starting the application?

**Comment by wimstefan** [comment]
Just to be sure I fulfil your demand I've made another clean install, switched to the branch and compiled everything without the faulthandler. This is the output:
```sh
 ./pytone -c conf/pytonerc
1
2
3
./pytone: line 2: 25438 Segmentation fault      python3 src/pytone.py "$@"
```

Hope this helps.

**Comment by joerg-lehmann** [comment]
Yes, that's the debugging output. Its hard to see the error, though. 
Neverthless, I pushed some small changes and made the debug output a bit more detailed. Please pull from this branch and recompile with
    python3 setup.py build_ext -fi

**Comment by wimstefan** [comment]
Hmm strange ... I did as you asked but I still get the same output?!? Here are the steps as I proceeded:
1. `rm -rf build/* src/*.so src/__pycache__`
2. `python3 ./setup.py build_ext -fi` with the following output:
``` running build_ext
building 'pytone.pcm' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
creating build/temp.linux-x86_64-3.6/src/pcm
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python3.6m -c src/pcm/pcm.c -o build/temp.linux-x86_64-3.6/src/pcm/pcm.o
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/pytone
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. build/temp.linux-x86_64-3.6/src/pcm/pcm.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/pytone/pcm.cpython-36m-x86_64-linux-gnu.so
building 'pytone.bufferedao' extension
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python3.6m -c src/bufferedao.c -o build/temp.linux-x86_64-3.6/src/bufferedao.o
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. build/temp.linux-x86_64-3.6/src/bufferedao.o -L/usr/lib64 -lao -lpython3.6m -o build/lib.linux-x86_64-3.6/pytone/bufferedao.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/pytone/pcm.cpython-36m-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-3.6/pytone/bufferedao.cpython-36m-x86_64-linux-gnu.so -> src
```

3. and finally running the program with `./pytone -c conf/pytonerc` resulting in:
```
1
2
3
./pytone: line 2: 12246 Segmentation fault      python3 src/pytone.py "$@"
```

`python3 --version` gives `Python 3.6.9`

**Comment by joerg-lehmann** [comment]
Ok, that's possible (and would leave me even more confused). However, to make sure that everything has been recompiled correctly, please try the current version of the branch, which only slightly changes the debug output.

**Comment by wimstefan** [comment]
Done. That's the output ...
```
1
2
3a
./pytone: line 2: 31907 Segmentation fault      python3 src/pytone.py "$@"
```

**Comment by joerg-lehmann** [comment]
Unfortunately, I could not yet identify why the code segfaults at this point. I pushed a slightly modified code to the repository, which also contains a debug output you should be able to capture with "pytone -d debug.txt". This file should contain two lines containing test_debug and test_error. Could you verify this, please. 

It is a bit like shooting in the dark as I cannot reproduce this bug by myself.

**Comment by wimstefan** [comment]
I apologize for all the hassle 😟

To make things even worse: I can't get the behaviour you were looking for with the new modifications. I still get the same output as [above](https://github.com/joerg-lehmann/PyTone/issues/4#issuecomment-562976020) and the `debug.txt` file remains empty ...
That happens even after I've deleted the directory with the cloned repository and created all new with the steps as described in [here](https://github.com/joerg-lehmann/PyTone/issues/4#issuecomment-562960328).

`dmesg` shows this error:
```
[Dec26 17:42] python3[30959]: segfault at 7f3e6b54bd90 ip 00007f3e693798e9 sp 00007fffc2e2cf20 error 7 in bufferedao.cpython-36m-x86_64-linux-gnu.so[7f3e69378000+2000]
[  +0.000003] Code: d2 48 8d 3d 77 0a 00 00 e8 d4 e7 ff ff ba 00 00 00 00 be 00 00 00 00 48 8d 3d 64 0a 00 00 e8 9e e8 ff ff 48 8b 15 d7 26 00 00 <48> 89 02 48 8d 3d 5f 0a 00 00 e8 a8 e7 ff ff 48 8b 05 b9 26 00 00
```
Python version: `Python 3.6.10`

I have to admit I feel quite stupid right now 🤔

**Comment by michael-hartmann** [comment]
Dear @wimstefan, Dear @joerg-lehmann,

I can reproduce the problem on my Linux machine. I am running Ubuntu 18.04 with python 3.5.2 from the Anaconda distribution. When running the problem I get a segmentation fault. I am trying to find the cause of the issue.

**Comment by michael-hartmann** [comment]
I don't fully understand the prolem yet, but declaring `error` as static seems to fix the problem, see PR #5.

**Comment by wimstefan** [comment]
I can confirm that the PR fixes the problem :)
Thank you so much @michael-hartmann for jumping in  and finding a solution! Now I can at least start up the application :)

For the next problem (playback of ogg-vorbis or flac files) I'll create a new issue ...
